PLANNING DOCS (rebase me)
This commit is a mess and needs broken up and rebased.

diff --git a/.github/workflows/dev.yml b/.github/workflows/dev.yml
--- a/.github/workflows/dev.yml
+++ b/.github/workflows/dev.yml
@@ -10,12 +10,12 @@
 name: "dev.yml"
 
 on:
-  pull_request: {}
+  pull_request: { }
   push:
     branches:
       - "main"
   merge_group:
-    types: ["checks_requested"]
+    types: [ "checks_requested" ]
   workflow_dispatch:
     inputs:
       debug_enabled:
@@ -58,17 +58,46 @@ jobs:
               - '!(README.md|LICENSE|design-docs/**|.gitignore|.github/**)'
               - '.github/workflows/dev.yml'
 
-  build:
-    needs: [ check_changes ]
+  commits:
+    name: "Deduce commit history"
+    permissions:
+      contents: "read"
+      pull-requests: "read"
+    runs-on: "ubuntu-latest"
+    outputs:
+      commits: "${{ steps.commits.outputs.commits }}"
+    steps:
+      - name: "install jq"
+        run: |
+          set -euxo pipefail
+          sudo apt-get update
+          sudo apt-get install --yes --no-install-recommends jq
+      - name: "Checkout"
+        uses: "actions/checkout@v4"
+        with:
+          persist-credentials: "false"
+          fetch-depth: "0"
+      - name: "commits"
+        id: "commits"
+        run: |
+          set -euxo pipefail
+          git rev-list --pretty=oneline \
+            ${{ github.event.pull_request.base.sha || 'main' }}..${{ github.event.pull_request.head.sha || 'HEAD' }} \
+            | sed -e  's/ /", "msg": "/' -e 's/^/{"ref": "/' -e 's/$/"}/' \
+            | jq --null-input --raw-output --compact-output '[inputs] | "commits=" + (. | tostring)' \
+            | tee -a "${GITHUB_OUTPUT}"
+
+  build-and-test:
+    name: "<${{ matrix.rust }}> ${{matrix.commit.msg}} [${{matrix.commit.ref}}]"
+    needs: [ check_changes, commits ]
     if: "${{ needs.check_changes.outputs.devfiles == 'true' }}"
     strategy:
       fail-fast: false
       matrix:
         rust:
           - "stable"
-          - "beta"
           - "nightly"
-    name: "Developer build (Rust ${{ matrix.rust }})"
+        commit: ${{ fromJSON(needs.commits.outputs.commits) }}
     runs-on: "lab"
     timeout-minutes: 45
     steps:
@@ -83,11 +112,12 @@ jobs:
         with:
           toolchain: "${{ matrix.rust }}"
           targets: "x86_64-unknown-linux-gnu,x86_64-unknown-linux-musl"
-      - name: "Checkout"
+      - name: "Checkout ${{matrix.commit.msg}}"
         uses: "actions/checkout@v4"
         with:
+          ref: "${{ matrix.commit.ref }}"
           persist-credentials: "false"
-          fetch-depth: "0"
+          fetch-depth: "1"
       - uses: "cargo-bins/cargo-binstall@main"
       - name: "install just"
         run: |
@@ -106,33 +136,13 @@ jobs:
           sudo apt-get --yes --no-install-recommends install pkg-config openssl libssl-dev colorized-logs
       - name: "install markdown-test-report"
         run: |
-          cargo binstall --no-confirm markdown-test-report
+          cargo install markdown-test-report
       - name: refresh-compile-env
         run: |
           just --yes debug=true refresh-compile-env
       - run: |
           just --yes debug=true fake-nix
 
-      - run: |
-          # Run a simple build for each separate commit (for "pull_request")
-          # or for the HEAD of the branch (other events).
-          set -eu -o pipefail
-          COMMITS=${{ github.sha }}
-          if [[ "${{ github.event_name == 'pull_request' }}" == "true" ]]; then
-            # Get all commits from Pull Request, in chronological order
-            COMMITS=$(git rev-list --reverse ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
-          fi
-          for commit in $COMMITS ; do
-            git checkout $commit || exit 1
-            printf "::group::Build commit %s\n" "$(git log --oneline --no-decorate -n 1)"
-            (just debug=true cargo +${{matrix.rust}} build --locked --profile=dev --target=x86_64-unknown-linux-gnu) || exit 1
-            printf "::endgroup::\n"
-          done
-          printf "::notice::HEAD remains at %s\n" "$(git log --oneline --no-decorate -n 1)"
-        continue-on-error: ${{ matrix.rust.optional }}
-
-      # At this stage, for Pull Requests, we're back to the HEAD of the branch,
-      # start running tests for different configurations.
       - name: "tests: rust ${{ matrix.rust }} profile=dev target=x86_64-unknown-linux-gnu"
         run: |
           export GITHUB_STEP_SUMMARY
@@ -166,7 +176,7 @@ jobs:
       - uses: "actions/upload-artifact@v4"
         if: ${{ always() }}
         with:
-          name: "test-results-${{ matrix.rust }}"
+          name: "results-${{ matrix.rust }}-${{ matrix.commit.ref }}"
           path: "target/nextest/"
 
       - name: "Setup tmate session for debug"
@@ -175,3 +185,17 @@ jobs:
         timeout-minutes: 60
         with:
           limit-access-to-actor: true
+
+
+  summary:
+    name: "Dev Test and Build"
+    if: ${{ always() }}
+    runs-on: "ubuntu-latest"
+    needs:
+      - build-and-test
+    steps:
+      - name: "Flag any build matrix failures"
+        if: ${{ needs.build-and-test.result != 'success' }}
+        run: |
+          >&2 echo "A critical step failed!"
+          exit 1
diff --git a/.github/workflows/sterile.yml b/.github/workflows/sterile.yml
--- a/.github/workflows/sterile.yml
+++ b/.github/workflows/sterile.yml
@@ -5,12 +5,12 @@
 name: "sterile.yml"
 
 on:
-  pull_request: {}
+  pull_request: { }
   push:
     branches:
       - "main"
   merge_group:
-    types: ["checks_requested"]
+    types: [ "checks_requested" ]
   workflow_dispatch:
     inputs:
       debug_enabled:
@@ -24,30 +24,34 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  check_changes:
-    name: "Deduce required tests from code changes"
+  commits:
+    name: "Track commits"
     runs-on: "ubuntu-latest"
     outputs:
       devfiles: "${{ steps.changes.outputs.devfiles }}"
+      commits: "${{ steps.commits.outputs.commits }}"
     steps:
+      - name: "install jq"
+        run: |
+          set -euxo pipefail
+          sudo apt-get update
+          sudo apt-get install --yes --no-install-recommends jq
       - name: "Checkout"
-        if: "${{ !github.event.pull_request }}"
         uses: "actions/checkout@v4"
         with:
           persist-credentials: "false"
           fetch-depth: "0"
-      - name: "Check code changes"
-        uses: "dorny/paths-filter@v3"
-        id: "changes"
-        with:
-          filters: |
-            devfiles:
-              - '!(README.md|LICENSE|design-docs/**|.gitignore|.github/**)'
-              - '.github/workflows/sterile.yml'
+      - name: "commits"
+        id: "commits"
+        run: |
+          set -euxo pipefail
+          git rev-list --pretty=oneline ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} \
+            | sed -e  's/ /", "msg": "/' -e 's/^/{"ref": "/' -e 's/$/"}/' \
+            | jq --null-input --raw-output --compact-output '[inputs] | "commits=" + (. | tostring)' \
+            | tee -a "${GITHUB_OUTPUT}"
 
   test:
-    needs: [ check_changes ]
-    if: "${{ needs.check_changes.outputs.devfiles == 'true' }}"
+    needs: [ commits ]
     permissions:
       contents: "read"
       packages: "read"
@@ -58,8 +62,8 @@ jobs:
       matrix:
         rust:
           - "stable"
-          - "nightly"
-    name: "Sterile test run (Rust ${{ matrix.rust }})"
+        commit: ${{ fromJSON(needs.commits.outputs.commits) }}
+    name: "${{matrix.commit.msg}} [${{matrix.commit.ref}} rust: ${{ matrix.rust }}]"
     steps:
       - name: "login to ghcr.io"
         uses: "docker/login-action@v3"
@@ -81,6 +85,9 @@ jobs:
 
       - name: "Checkout"
         uses: "actions/checkout@v4"
+        with:
+          ref: ${{ matrix.commit.ref }}
+          fetch-depth: '1'
 
       - name: "dev/gnu sterile test"
         if: ${{ always() }}
@@ -123,7 +130,7 @@ jobs:
             libssl-dev \
             openssl \
             pkg-config
-          cargo binstall --no-confirm markdown-test-report
+          cargo install markdown-test-report
 
       - name: "dev/gnu report"
         if: ${{ always() }}
@@ -156,7 +163,7 @@ jobs:
       - uses: "actions/upload-artifact@v4"
         if: ${{ always() }}
         with:
-          name: 'rust-${{matrix.rust}}-test-results'
+          name: 'rust-${{matrix.rust}}-test-results-${{matrix.commit.ref}}'
           path: "target/nextest"
 
       - name: "Setup tmate session for debug"
@@ -167,8 +174,7 @@ jobs:
           limit-access-to-actor: true
 
   push:
-    needs: [ check_changes ]
-    if: "${{ needs.check_changes.outputs.devfiles == 'true' }}"
+    needs: [ commits ]
     permissions:
       contents: "read"
       packages: "write"
@@ -179,8 +185,7 @@ jobs:
       matrix:
         rust:
           - "stable"
-          - "nightly"
-    name: "Push containers (Rust ${{ matrix.rust }})"
+    name: "push container image [rust ${{ matrix.rust }}]"
     steps:
       - name: "login to ghcr.io"
         uses: "docker/login-action@v3"
@@ -229,3 +234,17 @@ jobs:
         timeout-minutes: 60
         with:
           limit-access-to-actor: true
+
+  summary:
+    name: "Sterile Test and Build"
+    if: ${{ always() }}
+    runs-on: "ubuntu-latest"
+    needs:
+      - push
+      - test
+    steps:
+      - name: "Flag any build matrix failures"
+        if: ${{ needs.push.result != 'success' || needs.test.result != 'success' }}
+        run: |
+          >&2 echo "A critical step failed!"
+          exit 1
